"""GameDevWiki compendium builder (on-demand, API, budget-guarded).

Synthesises a skimmable "compendium" digest of the wiki's current state from a BOUNDED set
of inputs (to keep token cost low): the index catalog, the working thesis, the overview, the
most recent log entries, and the agent's health catalog. Writes out/compendium-<date>.md and
prints it. Never edits the curated index.md / log.md / thesis.md.

Run:
  python compendium.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from common import CONFIG, get_logger, safe_call, today

log = get_logger("compendium", "compendium.log")

VAULT = Path(CONFIG["vault_path"])
WIKI_ROOT = Path(CONFIG["wiki_root"])
OUT_DIR = Path(CONFIG["out_dir"])
RECENT_LOG_ENTRIES = 8


def _read(path: Path, limit_chars: int | None = None) -> str:
    if not path.exists():
        return ""
    text = path.read_text(encoding="utf-8")
    return text[:limit_chars] if limit_chars else text


def _recent_log(path: Path, n: int) -> str:
    """Last n '## [date] ...' entries from log.md."""
    if not path.exists():
        return ""
    text = path.read_text(encoding="utf-8")
    entries = re.split(r"(?=^## \[)", text, flags=re.MULTILINE)
    entries = [e for e in entries if e.startswith("## [")]
    return "".join(entries[-n:]).strip()


def build() -> Path:
    index_md = _read(VAULT / "index.md")
    thesis_md = _read(WIKI_ROOT / "syntheses" / "thesis.md")
    overview_md = _read(WIKI_ROOT / "overview.md")
    health_md = _read(OUT_DIR / "health.md")
    recent_log = _recent_log(VAULT / "log.md", RECENT_LOG_ENTRIES)

    system = (
        "You are a research-wiki compendium writer for a game-development knowledge base. "
        "You receive the wiki's catalog, working thesis, overview, recent activity log, and a "
        "health report. Write a skimmable compendium digest with these sections:\n"
        "## State of the field — the consolidated picture in 4-6 bullets, citing source ids (sNNN)\n"
        "## Recent additions — what changed lately (from the log)\n"
        "## Cross-cutting themes — connections spanning multiple sources\n"
        "## Gaps & TODOs — orphans, dangling links, and thin areas worth filling\n"
        "## Suggested next questions or sources\n"
        "Be precise, cited, and concise — bullets over prose. Do not invent pages or sources "
        "not present in the inputs."
    )
    user = (
        f"# index.md\n{index_md}\n\n"
        f"# thesis.md\n{thesis_md}\n\n"
        f"# overview.md\n{overview_md}\n\n"
        f"# recent log entries\n{recent_log}\n\n"
        f"# health report\n{health_md}"
    )

    body = safe_call(log, f"compendium {today()}", system, user)
    if body is None:
        print("Compendium NOT generated — Claude call failed or budget reached. See logs/compendium.log.")
        sys.exit(1)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUT_DIR / f"compendium-{today()}.md"
    header = (
        f"# Game Dev Wiki — Compendium ({today()})\n\n"
        f"_Auto-generated by the gamedevwiki agent. A synthesis, not a curated wiki page — "
        f"promote anything useful into wiki/ by hand._\n\n---\n\n"
    )
    out_path.write_text(header + body + "\n", encoding="utf-8")
    log.info("Wrote compendium to %s", out_path)
    return out_path


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")  # cp1252 consoles choke on →, —, etc.
    except Exception:  # noqa: BLE001
        pass
    out_path = build()
    print(out_path.read_text(encoding="utf-8"))
    print(f"\n[saved to {out_path}]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
