"""GameDevWiki agent handlers.

page_handler runs whenever a wiki page is created or modified. It rebuilds a health
catalog (no API call, free) at out/health.md:
  - orphan pages (no inbound [[links]] from anywhere in the vault)
  - dangling links = [[targets]] with no page yet — TODO pages worth creating (per the
    wiki's own convention: "a link to a page that doesn't exist yet is a TODO")
  - page counts per top-level wiki category

It deliberately does NOT touch the curated index.md / log.md / _PROGRESS.md, and does not
call Claude — that's compendium.py's job, run on demand.

Link matching is by basename (last path segment), because the wiki mixes absolute
([[wiki/concepts/foo]]) and relative ([[../../concepts/foo]]) link styles; basename is the
pragmatic common denominator for a health overview.
"""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

from common import CONFIG, append_to_file, get_logger, now_stamp

log = get_logger("handlers", "handlers.log")

WIKI_ROOT = Path(CONFIG["wiki_root"])
VAULT = Path(CONFIG["vault_path"])
OUT_DIR = Path(CONFIG["out_dir"])
HEALTH_FILE = OUT_DIR / "health.md"

WIKILINK = re.compile(r"\[\[([^\]]+)\]\]")
# Hub / entry-point pages that legitimately have no inbound links.
HUB_STEMS = {"index", "_index", "overview", "thesis", "glossary", "reading-paths"}
# Directories to skip when scanning the vault for link sources.
SKIP_DIRS = {"_agent", "_work", "_tools", ".obsidian", ".git", "raw"}


def _link_basename(target: str) -> str:
    """Normalise a [[link]] target to a lowercase basename: drop alias, anchor, .md, path.
    Handles both / and \\ separators and escaped pipes (\\|)."""
    target = target.replace("\\", "/").split("|", 1)[0].split("#", 1)[0].strip()
    if target.endswith(".md"):
        target = target[:-3]
    return target.rstrip("/").split("/")[-1].lower()


def _vault_md_files() -> list[Path]:
    out = []
    for p in VAULT.rglob("*.md"):
        if any(part in SKIP_DIRS for part in p.relative_to(VAULT).parts):
            continue
        out.append(p)
    return out


def _build_health() -> str:
    all_md = _vault_md_files()
    wiki_pages = list(WIKI_ROOT.rglob("*.md"))
    page_stems: dict[str, list[str]] = defaultdict(list)
    for page in wiki_pages:
        page_stems[page.stem.lower()].append(str(page.relative_to(WIKI_ROOT)).replace("\\", "/"))

    # A page "exists" if any markdown file in the vault (wiki/ or HotPotato/ etc.) has that stem.
    existing = {p.stem.lower() for p in all_md}

    # Collect every wikilink target across the vault, mapping basename -> source files.
    # Skip instruction/readme files: their example [[link]] syntax isn't a real reference.
    referenced: dict[str, set[str]] = defaultdict(set)
    for src in all_md:
        if src.name == "CLAUDE.md" or src.name.upper().startswith("README"):
            continue
        try:
            text = src.read_text(encoding="utf-8")
        except Exception as exc:  # noqa: BLE001
            log.warning("Could not read %s: %s", src, exc)
            continue
        rel_src = str(src.relative_to(VAULT)).replace("\\", "/")
        for m in WIKILINK.finditer(text):
            referenced[_link_basename(m.group(1))].add(rel_src)

    referenced_names = set(referenced.keys())

    orphans = sorted(
        rel
        for stem, rels in page_stems.items()
        if stem not in referenced_names and stem not in HUB_STEMS
        for rel in rels
    )
    dangling = sorted(name for name in referenced_names if name and name not in existing)

    cat_counts: dict[str, int] = defaultdict(int)
    for page in wiki_pages:
        parts = page.relative_to(WIKI_ROOT).parts
        cat = parts[0] if len(parts) > 1 else "(root)"
        cat_counts[cat] += 1

    lines = [
        "# Wiki health",
        "",
        f"_Auto-generated by the gamedevwiki agent — {now_stamp()}. Not curated; safe to ignore in Obsidian._",
        "",
        f"- Pages: **{len(wiki_pages)}**  ·  Orphans: **{len(orphans)}**  ·  Dangling links (TODO pages): **{len(dangling)}**",
        "",
        "## Pages per category",
    ]
    for cat in sorted(cat_counts):
        lines.append(f"- `{cat}` — {cat_counts[cat]}")

    lines += ["", "## Orphan pages (no inbound links)"]
    lines += [f"- [[wiki/{o[:-3] if o.endswith('.md') else o}]]" for o in orphans] or ["- (none)"]

    lines += ["", "## Dangling links — TODO pages worth creating"]
    if dangling:
        for name in dangling:
            srcs = sorted(referenced[name])
            example = srcs[0] + (f" (+{len(srcs) - 1} more)" if len(srcs) > 1 else "")
            lines.append(f"- `{name}` — referenced from {example}")
    else:
        lines.append("- (none)")

    lines.append("")
    return "\n".join(lines)


def page_handler(filepath: str) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    report = _build_health()
    # Overwrite (not append) — health is a current-state snapshot.
    HEALTH_FILE.write_text(report, encoding="utf-8")
    log.info("Rebuilt health catalog after change to %s -> %s",
             Path(filepath).name, HEALTH_FILE)


HANDLERS = {
    "pages": page_handler,
}
