<#
    Generic agent setup (Windows). GENERIC — copy unchanged into a new agent.

    Self-locating: uses its own folder ($PSScriptRoot) as the agent dir, so it works wherever
    you copy the agent to. Run from an ordinary (non-admin) PowerShell:
        powershell -ExecutionPolicy Bypass -File <agent-dir>\setup.ps1

    Steps: check python/git -> venv -> deps -> generate + install Startup VBS ->
    prompt for ANTHROPIC_API_KEY -> init vault git repo -> dry run -> checklist.
#>

$ErrorActionPreference = "Stop"

$AgentDir   = $PSScriptRoot
$Venv       = Join-Path $AgentDir "venv"
$VenvPy     = Join-Path $Venv "Scripts\python.exe"
$VbsPath    = Join-Path $AgentDir "run_watcher.vbs"
$StartupDir = [System.Environment]::GetFolderPath("Startup")

function Write-Step($n, $msg) { Write-Host "`n[$n] $msg" -ForegroundColor Cyan }
function Have($cmd) { return [bool](Get-Command $cmd -ErrorAction SilentlyContinue) }

if (-not (Test-Path (Join-Path $AgentDir "config.json"))) {
    throw "No config.json in $AgentDir. Copy config.template.json to config.json and edit it first."
}

# read agent_name and vault_path from config.json
$cfg = Get-Content (Join-Path $AgentDir "config.json") -Raw | ConvertFrom-Json
$AgentName = if ($cfg.agent_name) { $cfg.agent_name } else { "agent" }
$VaultDir  = $cfg.vault_path

Write-Step 1 "Checking dependencies (python, git)..."
function Ensure-Tool($cmd, $wingetId, $label) {
    if (Have $cmd) { Write-Host "  OK  $label: $((Get-Command $cmd).Source)"; return }
    Write-Host "  MISSING  $label" -ForegroundColor Yellow
    if (Have "winget") {
        if ((Read-Host "       Install $label via winget? (y/n)") -eq "y") {
            winget install --id $wingetId -e --accept-source-agreements --accept-package-agreements
        } else { throw "$label is required." }
    } else { throw "$label missing and winget unavailable." }
}
Ensure-Tool "python" "Python.Python.3.12" "Python 3"
& python -m pip --version | Out-Null
if ($LASTEXITCODE -ne 0) { throw "pip not working under python." }
Ensure-Tool "git" "Git.Git" "Git"

Write-Step 3 "Creating venv at $Venv ..."
if (Test-Path $VenvPy) { Write-Host "  reusing existing venv" } else { & python -m venv $Venv }
if (-not (Test-Path $VenvPy)) { throw "venv creation failed." }

Write-Step 4 "Installing Python dependencies..."
& $VenvPy -m pip install --upgrade pip | Out-Null
& $VenvPy -m pip install -r (Join-Path $AgentDir "requirements.txt")
if ($LASTEXITCODE -ne 0) { throw "pip install failed." }

Write-Step 5 "Creating log + watch directories..."
New-Item -ItemType Directory -Force -Path (Join-Path $AgentDir "logs") | Out-Null
foreach ($wp in $cfg.watch_paths.PSObject.Properties) {
    $p = if ($wp.Value -is [string]) { $wp.Value } else { $wp.Value.path }
    if ($p) { New-Item -ItemType Directory -Force -Path $p | Out-Null }
}
if ($VaultDir) { New-Item -ItemType Directory -Force -Path $VaultDir | Out-Null }

Write-Step 6 "Generating + installing Startup VBS..."
$pyw = Join-Path $Venv "Scripts\pythonw.exe"
$watcher = Join-Path $AgentDir "watcher.py"
$vbs = @"
' Auto-generated by setup.ps1 for agent: $AgentName
Dim sh : Set sh = CreateObject("WScript.Shell")
sh.Run "$('"' + $pyw + '"') $('"' + $watcher + '"')", 0, False
"@
Set-Content -Path $VbsPath -Value $vbs -Encoding ASCII
Copy-Item -Path $VbsPath -Destination (Join-Path $StartupDir "$AgentName-watcher.vbs") -Force
Write-Host "  Installed $AgentName-watcher.vbs to $StartupDir"

Write-Step 7 "Configuring ANTHROPIC_API_KEY..."
if ([System.Environment]::GetEnvironmentVariable("ANTHROPIC_API_KEY", "User")) {
    Write-Host "  Already set for this user; leaving unchanged."
} else {
    $key = Read-Host "  Paste ANTHROPIC_API_KEY (hidden)" -AsSecureString
    $plain = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($key))
    if ([string]::IsNullOrWhiteSpace($plain)) {
        Write-Host "  Skipped. Set later: setx ANTHROPIC_API_KEY <key>" -ForegroundColor Yellow
    } else {
        setx ANTHROPIC_API_KEY $plain | Out-Null
        $env:ANTHROPIC_API_KEY = $plain
        Write-Host "  Saved to user environment."
    }
}

Write-Step 8 "Vault git repo..."
if (-not $cfg.git_auto_commit) {
    Write-Host "  git_auto_commit is false; not initialising a repo at $VaultDir."
} elseif ($VaultDir -and -not (Test-Path (Join-Path $VaultDir ".git"))) {
    Push-Location $VaultDir
    git init | Out-Null
    if (-not (git config user.email)) { git config user.email "agent@localhost" }
    if (-not (git config user.name))  { git config user.name  "Agent" }
    Pop-Location
    Write-Host "  git repo initialised at $VaultDir"
} else { Write-Host "  vault already a repo (or no vault_path)." }

Write-Step 9 "Dry run..."
& $VenvPy $watcher --dry-run

Write-Step 10 "Done. Start now without logging out:"
Write-Host "    wscript `"$StartupDir\$AgentName-watcher.vbs`""
Write-Host "  Or foreground (live logs):  & `"$VenvPy`" `"$watcher`""
